const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR';
const REMOVE_ITEM_REQUEST = 'REMOVE_ITEM_REQUEST';
const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
const REMOVE_ITEM_ERROR = 'REMOVE_ITEM_ERROR';

const INCREMENT_ITEM = 'INCREMENT_ITEM';
const DECREMENT_ITEM = 'DECREMENT_ITEM';

export { ADD_ITEM_REQUEST, ADD_ITEM_SUCCESS, ADD_ITEM_ERROR, REMOVE_ITEM_REQUEST, REMOVE_ITEM_SUCCESS, REMOVE_ITEM_ERROR,
          INCREMENT_ITEM, DECREMENT_ITEM}
