const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';

const ADD_EDIT_PRODUCT_REQUEST = 'ADD_EDIT_PRODUCT_REQUEST';
const ADD_EDIT_PRODUCT_SUCCESS = 'ADD_EDIT_PRODUCT_SUCCESS';
const ADD_EDIT_PRODUCT_ERROR = 'ADD_EDIT_PRODUCT_ERROR';

export {
  FETCH_PRODUCT_REQUEST,
  FETCH_PRODUCT_SUCCESS,
  FETCH_PRODUCT_ERROR,
  ADD_EDIT_PRODUCT_REQUEST,
  ADD_EDIT_PRODUCT_SUCCESS,
  ADD_EDIT_PRODUCT_ERROR
}
