const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST'
const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'
const FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR'

const ADD_EDIT_CATEGORY_REQUEST = 'ADD_EDIT_CATEGORY_REQUEST'
const ADD_EDIT_CATEGORY_SUCCESS = 'ADD_EDIT_CATEGORY_SUCCESS'
const ADD_EDIT_CATEGORY_ERROR = 'ADD_EDIT_CATEGORY_ERROR'

export { 
    FETCH_CATEGORY_REQUEST, 
    FETCH_CATEGORY_SUCCESS, 
    FETCH_CATEGORY_ERROR,
    ADD_EDIT_CATEGORY_REQUEST, 
    ADD_EDIT_CATEGORY_SUCCESS,
    ADD_EDIT_CATEGORY_ERROR 
  }